### PR TITLE
Merge my branch with dev 

### PR DESCRIPTION
**Pull request by lauracarlton**

### CODE REVIEW

**Comment by dboas** [comment]
@avolu this pull request from Laura looks good to me. Mainly it brings her her additions to motion correction and artifactions. She also fixed the issue you and I worked on in to_epochs. And has a few other changes you should look over. Have you had a chance to look at it?

**Comment by avolu** [comment]
@dboas i had a brief look and think we can merge most of it, but will have to do a bit of a thorough code review regarding usage of xarray masks and elements that might have changed in the meantime. @lauracarlton all your functions use and generate xarray masks the way we introduced it a few months back, right?

**Review by avolu — APPROVED** [review]
Reviewed by @dboas and @avolu today
Revisit/check:

1) artifact.py: Global variables CLEAN and TAINTED (L309/10): why here outside of functions?
2) delete motion_correct_spline_2: we did a code diff, [  ]spline seems to be newer and with less errors. will delete spline_2, assuming its an old copy.

Open topics general:
I) rename modules artifact.py/motion_correct.py or move functionality to create a clear functional distinction
II) check/implement (if not existent): recording container should also incoroporate tInc timeseries xarray "mask". Should this go under masks? Isnt this the same as a standard xarray mask?

**Review by dboas — APPROVED** [review]
thanks for making my requested changes

**Pull request merged**
