### PR TITLE
changes to scalp_plot and bug fixes in motion_correct

### PR DESCRIPTION
**Pull request by lauracarlton**
1. add 10-5 EEG info to data folder so that it is accessible by scalp_plot
2. bug fix in output dimensions of splineSG and PCArecurse so they match the input dimensions
3. fixed output warning about downcasting xarray to numpy array

### CODE REVIEW

**Comment by dboas** [comment]
@lauracarlton 
I wonder if you could do a pull request for the motion correction stuff separate from the others. I am comfortable reviewing and approving the motion correction stuff, but not the changes you made to the plot and ICA files.

**Comment by lauracarlton** [comment]
I will close this pull request and split it into two.

**Comment by lauracarlton** [comment]
> @lauracarlton I wonder if you could do a pull request for the motion correction stuff separate from the others. I am comfortable reviewing and approving the motion correction stuff, but not the changes you made to the plot and ICA files.

I am trying to figure out how to do this - it seems like the pull request includes all commits made to the branch. I can try splitting these changes into two different branches and then creating two different pull requests from there?

**Comment by dboas** [comment]
That is probably the right way to do it… two separate branches. Sorry for the trouble.


From: Laura Carlton ***@***.***>
Date: Friday, August 16, 2024 at 1:33 PM
To: ibs-lab/cedalion ***@***.***>
Cc: Boas, David ***@***.***>, Review requested ***@***.***>
Subject: Re: [ibs-lab/cedalion] changes to scalp_plot and bug fixes in motion_correct (PR #27)

@lauracarlton<https://github.com/lauracarlton> I wonder if you could do a pull request for the motion correction stuff separate from the others. I am comfortable reviewing and approving the motion correction stuff, but not the changes you made to the plot and ICA files.

I am trying to figure out how to do this - it seems like the pull request includes all commits made to the branch. I can try splitting these changes into two different branches and then creating two different pull requests from there?

**Review by emiddell — APPROVED** [review]
Hi @lauracarlton, thank you for the PR. I just moved the logic to derive the data file paths into the function `cedalion.data.get` to make accessing these files easier. Please feel free to merge it.

**Pull request merged**
